---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo-fargate
  region: ap-northeast-2
fargateProfiles:
  - name: loggeth-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: loggeth-fargate
